version: "3"

networks:
  dev:

volumes:
  data:

services:

  cronpub:
    container_name: cronpub
    build:
      args:
        PROJECT: cronpub
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ./src:/go/src/cronpub/src
      - ./settings.yaml:/settings.yaml
    environment:
      APP_ENV: development
      REDIS_ADDRESS: redis:6379
      REDIS_NETWORK: tcp
    networks:
      - dev
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    command: redis-server --appendonly yes
    logging:
      driver: none
    volumes:
      - data:/data
    networks:
      - dev
