telegram:
  bot_token: token
  caption: caption
  chat_name: chat
  crons:
  - "0 */2 * * * *"

scraper:
  links:
  - https://www.reddit.com/r/___subreddit___/top.json?limit=5
  crons:
  - "0 */5 * * * *"
